version: "3.8"
services:
  backend:
    image: sjknapp/Group3-backend
    build: ./Group3-Backend-Spring
    ports:
    - target: 8080
      published: 8081

# nginx:
#    image: nginx:latest
#    ports:
#    - target: 80
#      published: 80
#      protocol: tcp
#    volumes:
#    - type: bind
#      source: ./nginx/nginx.conf
#      target: /etc/nginx/nginx.conf
